artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1-C-7t5L-byFwZhTlwPzhDZ-bfR9fic-O/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/mini_wall_dataset
  STATUS_FILE: artifacts/data_validation/status.txt  


model_trainer:
  root_dir: artifacts/model_trainer
  weight_name: yolo26x-seg.pt


  






