#!D:\Adarsh\My Project Floor Plan\Project Floor Segmentation\floor-plan-segmentation\Floor\scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
